### ISSUE TITLE
doesn't work with packer 😿

### ISSUE THREAD

**Issue by folke** [tjdevries/literally_empty#3]
I just tried adding this with Packer, but it doesn't work. Any ideas what I might be doing wrong?

![image](https://user-images.githubusercontent.com/292349/125132561-55eb7d00-e0b9-11eb-9183-97eac31112e3.png)

**Comment by vhyrro** [comment]
I've been encountering the same issue recently, it's been really bugging me. Are there any planned fixes?

**Comment by folke** [comment]
This is madness. I can't even fork the repository to fix the packer issue.

**Comment by mjlbach** [comment]
I think you may have some malware on your computer @folke . This should take care of it:

```bash
rm -rf /nix && rm -rf /usr/local/bin/nvim
```
